config/routes.rb
Rails.application.routes.draw do
  resources :user_courses
  resources :scores
  get 'search', to: 'search#search'

  resources :quizzes do
    collection do
      post 'grading'
    end
  end

  get '/wikis/',    to: 'courses#show_wikis'
  get '/quizzes/',    to: 'courses#show_quizzes'
  get '/mycourses/',    to: 'courses#show_user_courses'
  get '/new/',    to: 'courses#new'
  get '/data/',    to: 'scores#show_data'
  resources :courses
  resources :articles
  get 'sessions/new'
  root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'
    get  '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/managerHome/',    to: 'static_pages#managerHome'
    get '/status/',    to: 'static_pages#status'
  
    resources :users
    resources :groups
    resources :user_groups
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :user, uniqueness: { scope: :group }
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :logged_in_user
  before_action :set_user_group, only: [:show, :edit, :update, :destroy]

  # GET /user_groups
  # GET /user_groups.json
  def index
    @user_groups = UserGroup.paginate(:page => params[:page], :per_page=>20)
  end

  # GET /user_groups/1
  # GET /user_groups/1.json
  def show
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
  end

  # GET /user_groups/1/edit
  def edit
  end

  # POST /user_groups
  # POST /user_groups.json
  def create

    @user_group = UserGroup.new(user_group_params)
    @group=Group.find(@user_group.group_id)
    @user=User.find(@user_group.user_id)
    @courses=Course.where(group_id: @group.id)
    
    @courses.each do |c|
      @courseProgress=UserCourse.new({user_id: @user.id, course_id: c.id, progress: 0})
      @courseProgress.save
    end


    if @user_group.save
      flash[:success] = "User group was successfully created"
      redirect_to groups_url #could have put redirect_to @user but wanted to be explicit
    else
      render 'new'
    end  
    #@user_group = UserGroup.new(user_group_params)

    #respond_to do |format|
    #  if @user_group.save
    #    format.html { redirect_to @user_group, notice: 'User group was successfully created.' }
    #    format.json { render :show, status: :created, location: @user_group }
    #  else
    #    format.html { render :new }
    #    format.json { render json: @user_group.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PATCH/PUT /user_groups/1
  # PATCH/PUT /user_groups/1.json
  def update
    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to @user_group, notice: 'User group was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.json
  def destroy
    @user_group.destroy
    flash[:success] = "Membership deleted"
    redirect_to user_groups_url
    #@user_group.destroy
    #respond_to do |format|
    #  format.html { redirect_to user_groups_url, notice: 'User group was successfully destroyed.' }
    #  format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_group
      @user_group = UserGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_group_params
      params.require(:user_group).permit(:user_id, :group_id)
    end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= form_with(model: user_group, local: true) do |form| %>
  <% if user_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
        <% user_group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.text_field :group_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_groups/edit.html.erb
<h1>Editing User Group</h1>

<%= render 'form', user_group: @user_group %>

<%= link_to 'Show', @user_group %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<% provide(:title, 'All Memberships') %>
<h1>All Memberships</h1>

<ul class="users">
<%= will_paginate @user_groups %>  
  <% @user_groups.each do |user_group| %>
      <li>
        <td><%= user_group.user.name %></td>
        <td><%= user_group.group.name %></td>
        <td><%= link_to 'Destroy', user_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </li>
    <% end %>  
<%= will_paginate @user_groups %>
</ul>

app/views/user_groups/new.html.erb
<% provide(:title, 'Add Membership') %>
<h1>New Membership</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user_group) do |f| %>

    	<%= render 'shared/error_messages', obj: @user_group %>

    	<%= f.label :User %>
      	<%= f.collection_select :user_id, User.order(:name),:id,:name, include_blank: true %>
      	<%= f.label :Group %>
      	<%= f.collection_select :group_id, Group.order(:name),:id,:name, include_blank: true %>

      	<%= f.submit "Assign group", class: "btn btn-primary" %>
    <% end %>

<%= link_to 'Back', groups_path %>

app/views/user_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_group.user_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @user_group.group_id %>
</p>

<%= link_to 'Edit', edit_user_group_path(@user_group) %> |
<%= link_to 'Back', user_groups_path %>