config/routes.rb
Rails.application.routes.draw do
  resources :user_courses
  resources :scores
  get 'search', to: 'search#search'

  resources :quizzes do
    collection do
      post 'grading'
    end
  end

  get '/wikis/',    to: 'courses#show_wikis'
  get '/quizzes/',    to: 'courses#show_quizzes'
  get '/mycourses/',    to: 'courses#show_user_courses'
  get '/new/',    to: 'courses#new'
  get '/data/',    to: 'scores#show_data'
  resources :courses
  resources :articles
  get 'sessions/new'
  root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'
    get  '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/managerHome/',    to: 'static_pages#managerHome'
    get '/status/',    to: 'static_pages#status'
  
    resources :users
    resources :groups
    resources :user_groups
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/score.rb
class Score < ApplicationRecord
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :logged_in_user
  before_action :set_score, only: [:show, :edit, :update, :destroy]
  before_action :manager_user,   only: [:index]
  before_action :admin_user, only: :destroy

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  def show_data
    @scores = Score.all
    @articles=Article.all
    if(params[:article_id].blank?)
      @currentArticle=Article.find(1)
    else
      @currentArticle=Article.find(params[:article_id])
    end
    array=[]
    for a in 0..9 do
      bin=a*10
      array[a]=Score.where(article_id: params[:article_id],score: bin..bin+10).count
    end
    @test=[["0-10%",array[0]],["10-20%",array[1]],["20-30%",array[2]],["30-40%",array[3]],["40-50%",array[4]],["50-60%",array[5]],["60-70%",array[6]],
    ["70-80%",array[7]],["80-90%",array[8]],["90-100%",array[9]]]
    @averageScore=Score.where(article_id: params[:article_id]).average(:score)
    attempts=Score.where(article_id: params[:article_id])
    hash=attempts.distinct.group(:user_id).count()

    count=0
    sum=0
    hash.each do |key, value|
      count=count+1
      sum=sum+value
    end
    if(count!=0)
      @averageAttempts=sum.to_f/count.to_f
    end
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy

    flash[:success] = "Attempt deleted"
    redirect_to scores_url

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:user_id, :article_id, :score)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

      # Confirms a manager user.
    def manager_user
      redirect_to(root_url) unless current_user.manager?
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_with(model: score, local: true) do |form| %>
  <% if score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :article_id %>
    <%= form.number_field :article_id %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Scores</h1> 

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>


 <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= User.find(score.user_id).name %></td>
        <td><%= Article.find(score.article_id).title %></td>
        <td><%= score.score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= User.find(@score.user_id).name %>
</p>

<p>
  <strong>Quiz:</strong>
  <%= Article.find(@score.article_id).title%>
</p>

<p>
  <strong>Score:</strong>
  <%= @score.score %>%
</p>

app/views/scores/show_data.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @currentArticle.title %></h1>
  <p>
    <%= form_tag "", id: "score-form", method: :get do %>
      <%= select_tag 'article_id', options_for_select(@articles.collect{ |a| [a.title, a.id] }) %>
      <%=submit_tag "Filter", disable_with: 'Filtering...', :style => "width:400px;", class: 'btn btn-primary' %>
    <%end%>
  </p>

  <%= column_chart @test %>

  <h5>Mean Score:</h5> <%= @averageScore %>
  <h5>Mean Attempts:</h5> <%= @averageAttempts %>

<br/>
<br/>
<br/>
<%= link_to 'All scores', scores_path%>