config/routes.rb
Rails.application.routes.draw do
  resources :user_courses
  resources :scores
  get 'search', to: 'search#search'

  resources :quizzes do
    collection do
      post 'grading'
    end
  end

  get '/wikis/',    to: 'courses#show_wikis'
  get '/quizzes/',    to: 'courses#show_quizzes'
  get '/mycourses/',    to: 'courses#show_user_courses'
  get '/new/',    to: 'courses#new'
  get '/data/',    to: 'scores#show_data'
  resources :courses
  resources :articles
  get 'sessions/new'
  root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'
    get  '/signup',  to: 'users#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/managerHome/',    to: 'static_pages#managerHome'
    get '/status/',    to: 'static_pages#status'
  
    resources :users
    resources :groups
    resources :user_groups
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	require 'elasticsearch/model'
	belongs_to :course

	validates :title, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }

	validates :category, presence: true, length: { maximum: 50 }


	class Article < ActiveRecord::Base
		include Elasticsearch::Model
		include Elasticsearch::Model::Callbacks
	end
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :articles
	has_many :user_courses, :dependent => :destroy
	has_many :users, through: :user_courses

	validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :user_groups, :dependent => :destroy
  	has_many :users, through: :user_groups

	validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :quiz
	has_many :answers, :dependent => :destroy
	accepts_nested_attributes_for :answers, reject_if: :all_blank, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
	has_many :questions, :dependent => :destroy
	accepts_nested_attributes_for :questions, reject_if: :all_blank, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/score.rb
class Score < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_groups, :dependent => :destroy
  	has_many :groups, through: :user_groups
  	has_many :user_courses, :dependent => :destroy
  	has_many :courses, through: :user_courses

	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
	
end

app/models/user_course.rb
class UserCourse < ApplicationRecord
  belongs_to :user
  belongs_to :course

  validates :user, uniqueness: { scope: :course }
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :user, uniqueness: { scope: :group }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_user
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :manager_user,   only: [:index]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.paginate(:page => params[:page], :per_page=>20)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @members = @group.users
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    if @group.save
      #log_in @user
      flash[:success] = "Group created"
      redirect_to group_url(@group) #could have put redirect_to @user but wanted to be explicit
    else
      render 'new'
    end    
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:success] = "Group updated"
      redirect_to @group
    else
      render 'edit'
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    Group.find(params[:id]).destroy
    flash[:success] = "Group deleted"
    redirect_to groups_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Confirms a manager user.
  def manager_user
    redirect_to(root_url) unless current_user.manager?
  end
    
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Employee Training System"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper

    def get_wikis (course)
            @article_wikis = Article.find_by_sql ["select * from articles where course_id = ? and category = ?", @course.course_id, "Wiki"]
    end

    def get_quizzes (wiki_id)
            @article_quizzes = Quiz.find_by_sql ["select * from quizzes where article_id = ?", "#{wiki_id}"]
    end

    def set_wiki_global_id(wiki_id)
        $article_wiki_id = "#{wiki_id}"
        # @article_wiki_by_id = Article.find_by_sql ["select * from articles where id = ?", "#{wiki_id}"]
    end

    def get_wiki_by_id(wiki_id)
        @article_wiki_id = "#{wiki_id}"
        @article_wikis = Article.find_by_sql ["select * from articles where id = ?", @article_wiki_id]
    end
    
    def set_quiz_global_id(quiz_id)
        $article_quiz_id = "#{quiz_id}"
    end

    def get_quiz_by_id(quiz_id)
        @article_quiz_id = "#{quiz_id}"
        @article_quizs = Article.find_by_sql ["select * from articles where id = ?", @article_quiz_id]
    end

    def get_progress(userID, courseID)
        return UserCourse.where(:user_id => userID, :course_id => courseID).pluck(:progress).first
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
	def get_users()
		@users = User.find(session[:user_id])
	end

	def get_quiz1()
		@quiz1 = Quiz.find(session[:article_id])
	end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Returns true if the user is the current user.
  def current_user?(user)
    user == current_user
  end

  def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	 # Confirms a manager user.
    def manager_user
      redirect_to(root_url) unless current_user.manager?
    end
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<li>
  <%= link_to group.name, group %>
  <% if current_user.admin? %>
    | <%= link_to "delete", group, method: :delete, data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/groups/edit.html.erb
<% provide(:title, "Edit group") %>
<h1>Edit Group</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@group) do |f| %>

    	<%= render 'shared/error_messages', obj: @group %>

    	<%= f.label :name %>
      	<%= f.text_field :name, class: 'form-control' %>

      	<%= f.submit "Update group", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/groups/index.html.erb
<% provide(:name, 'All groups') %>
<h1>All groups</h1>

<%= pie_chart UserGroup.joins(:group).group('groups.name').count, library: {legend:{position: "bottom"}} %>

<ul class="users">
<%= will_paginate @groups %>  
  <% @groups.each do |group| %>
    <%#= "group:"%><%#=group.id%>
    <%= render group %>  
  <% end %> 
<%= will_paginate @group %>
</ul>

<% if current_user.manager? %>
  <%= link_to 'Create Group', new_group_path %> | 
  <%= link_to 'Assign User', new_user_group_path %>
<% end %>

app/views/groups/new.html.erb
<% provide(:title, 'Add Group') %>
<h1>New Group</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@group) do |f| %>

    	<%= render 'shared/error_messages', obj: @group %>

    	<%= f.label :name %>
      	<%= f.text_field :name, class: 'form-control' %>

      	<%= f.submit "Create group", class: "btn btn-primary" %>
    <% end %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @group.name %>
      </h1>
    </section>
  </aside>
</div>



<p id="notice"><%= notice %></p>

<% @members.each do |member| %>
    <ul>
      <td><%= link_to member.name, member %></td>
    </ul>
<% end %>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>